version: '3'
services:
  db:
    image: 'postgres:14.4-alpine'
    environment:
      - POSTGRES_PASSWORD=db_pwd
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
  api:
    container_name: 'api'
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=db_pwd
    env_file: .env
  ui:
    container_name: 'ui'
    build:
      context: ui
      dockerfile: Dockerfile.dev
    volumes:
      - /ui/node_modules
      - ./ui:/ui
  nginx:
    container_name: 'nginx'
    depends_on:
      - api
      - ui
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    ports:
      - '5000:80'
