default: &default
  adapter: postgresql
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: startup_development

test:
  <<: *default
  database: startup_test

production:
  <<: *default
  database: startup
