env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
    import/resolver:
      node:
        extensions:
          - '.ts'
          - '.tsx'
          - '.js'
          - '.jsx'
rules:
  import/extensions: off
  react/react-in-jsx-scope: off
  import/prefer-default-export: off
  react/function-component-definition: off
  semi: off
  react/jsx-filename-extension:
    - 2
    - extensions:
        - '.tsx'
