FROM ruby:3.1.0
RUN apt update -qq && apt install -y nano
ENV RAILS_ENV=development
ENV EDITOR=nano

WORKDIR '/api'

COPY Gemfile Gemfile.lock ./
RUN bundle config unset frozen
RUN bundle install

COPY ./entrypoint.sh /

COPY . .

RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["bundle", "exec", "rails", "server", "-p", "3060", "-b", "0.0.0.0"]
