FROM ruby:3.1.0

WORKDIR '/api'

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY ./entrypoint.sh /

COPY . .

RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["bundle", "exec", "rails", "server", "-p", "3060", "-b", "0.0.0.0"]
