source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

gem 'pg', "~> 1.4.1"
gem "bootsnap", require: false
gem "puma", "~> 5.0"
gem "rails", "~> 7.0.3"
gem "sidekiq", "~> 6.5"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
