# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'

gem 'bootsnap', require: false
gem 'pg', '~> 1.4.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.3.1'
gem 'sidekiq', '~> 6.5'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'pry'
  gem 'rubocop', '~> 1.31', require: false
  gem 'rubocop-minitest', '~> 0.20', require: false
  gem 'rubocop-rails', '~> 2.15', require: false
end
